### ISSUE TITLE
Elements overtlaapping in Dialogue

### ISSUE THREAD

**Issue by d0utone** [akib1997/lhoste#2]
![image](https://user-images.githubusercontent.com/7131243/121647247-7f9f8d00-ca96-11eb-830c-a4196aed6a7d.png)

**Comment by MeAkib** [comment]
Hi Akin,

I didn't find this issue. Which browser you're using? I'm using Windows and Edge and it's working on Chrome, Firefox also.

**Comment by d0utone** [comment]
Ok, seems to be solved. Came very sporadically.
